feat(plugins): add synchronous methods for videoroom plugin
Ghamza-Jd/jarust pull request #117
Opened 2024-07-31 20:04 UTC by koefmatt

This PR implements the API of the Janus videoroom plugin. The following features have so far been implemented:

- [x] Setup
- [x] Sync
    - [x] Create
    - [x] Destroy
    - [x] Edit
    - [x] Exists
    - [x] List
    - [x] Allowed
    - [x] Kick
    - [x] Moderate
    - [x] enable_recording
    - [x] listparticipants

2024-07-31 20:07 UTC, koefmatt commented
I've been working on this plugin privately for a while and just saw that you've started to work on it yourself. Please let me know if you like the style. The example provided tests most of the methods except for the ones involving participants as joining is an async operation. I have started on async and events as well, but that is still untested and incomplete.

2024-08-01 08:21 UTC, Ghamza-Jd commented
@koefmatt Wow ⭐, thanks for your contribution! I'll have a proper look and test this evening, a comment about the style, we were using a similar approach but we found it verbose, since we had to create two structs and an `impl` block, which made it verbose.

In the example below we only had to define a single struct for this request

```rust
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Default, Serialize)]
pub struct CreateRoomOptions {
    /// unique numeric ID, chosen by plugin if missing
    #[serde(skip_serializing_if = "Option::is_none")]
    pub room: Option<Identifier>,
    // ...
}

pub async fn create_room_with_config(
  &self,
  options: CreateRoomOptions,
  timeout: Duration,
) -> JaResult<RoomCreatedRsp> {
    let mut message = serde_json::to_value(options)?;
    message["request"] = "create".into();
    self.handle
        .send_waiton_rsp::<RoomCreatedRsp>(message, timeout)
        .await
}
```

And in this example we didn't define any struct for the request body
```rust
pub async fn list_rooms(&self, timeout: Duration) -> JaResult<Vec<Room>> {
    let message = json!({
        "request": "list"
    });
    let response = self
        .handle
        .send_waiton_rsp::<ListRoomsRsp>(message, timeout)
        .await?;
    Ok(response.list)
}
```

2024-08-01 09:30 UTC, koefmatt commented
> we were using a similar approach but we found it verbose

Yeah, I figured as much. I based this plugin off of an older version of your audiobridge implementation. Changing it wouldn't be problem and would reduce complexity. I'll get to it tonight.

2024-08-01 16:37 UTC, Ghamza-Jd requested changes
I've tested it and it works nicely! 🚀
Small comments one using the `Identifier` enum instead of `u64` so that when someone enable `string_ids` in the configs.
Another comment is on the style as you stated before that comes following the old aproach we had on the audio bridge.

2024-08-01 16:37 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/README.md
We can remove that, we're tracking the progress here #101

2024-08-01 16:37 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/responses.rs
> +    pub room: u64,
IDs could be string if we uncommented this bin the `videoroom.jcfg`:
```txt
string_ids = true
```

In the `audiobridge` we created an identifier enum
```rust
pub enum Identifier {
    /// String Identifier
    String(String),
    /// Unsigned Integer Identifier
    Uint(u64),
}
```

We can move it to a common place for both plugins

2024-08-01 16:37 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/responses.rs
> +    pub id: u64,
This should also be of type `Identifier`

2024-08-01 16:37 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/responses.rs
> +pub enum VideoRoomPluginEvent {
We can remove this and use the pattern we've used on other structs to parse `ListRtpForward`

2024-08-01 16:37 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/handle.rs
> +
A self preference style, since editors can collapse the blocks

```suggestion
//
// synchronous methods
//
impl VideoRoomHandle {
```

And when introducing the asynchronous methods, they can be a new impl block

2024-08-01 16:37 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/responses.rs
> +}
This can be removed once we remove `VideoRoomPluginEvent`

2024-08-01 16:37 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/responses.rs
> +}
These could also be deleted after `VideoRoomPluginEvent`

2024-08-01 16:37 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/responses.rs
> +    pub publisher_id: u64,
This also should be an `Identifier`

2024-08-01 16:37 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/messages.rs
> +    pub room: Option<u64>,
```suggestion
    pub room: Option<Identifier>,
```

2024-08-01 16:37 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/messages.rs
> +    pub id: Option<u64>,
```suggestion
    pub id: Option<Identifier>,
```

2024-08-01 16:37 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/messages.rs
> +    pub feed: u64,
```suggestion
    pub feed: Identifier,
```

2024-08-01 17:48 UTC, koefmatt commented on jarust_plugins/src/video_room/responses.rs
> +}
Oh, these snuck in from my preliminary implementation of events and async methods. Comitted by mistake but I'd keep them here since they will come back eventually.

2024-08-01 21:47 UTC, Ghamza-Jd approved these changes
Smashing!

2024-08-01 21:48 UTC, merged