Draft: feat(plugins): Add async methods and events for Videoroom plugin
Ghamza-Jd/jarust pull request #118
Opened 2024-08-08 18:50 UTC by koefmatt

This PR implements the asynchronous methods and associated events of the Janus videoroom plugin API. Additionally it adds the missing synchronous methods for RTP forwarding.

It's difficult to implement the events as the documentation seems to be wrong or at least incomplete for some of them. Some of the provided structs can't be deserialized easily because they share common keys and values for identification.

2024-08-11 19:15 UTC, Ghamza-Jd commented
Nice, Thanks!

I'll take a look at this tomorrow morning.

2024-08-12 04:15 UTC, Ghamza-Jd commented
> It's difficult to implement the events as the documentation seems to be wrong or at least incomplete for some of them.

No worries, planning for `1.0` which will include stabilisation and more testing. Part of it is APIs that seem a bit fiddly and/or poorly documented can be flagged as `unstable` until we try them in some sample apps.

2024-08-30 09:19 UTC, Ghamza-Jd requested changes
Great work!
I've added some comments on how to deserialize the event variant of the video room event

2024-08-30 09:19 UTC, Ghamza-Jd commented on jarust_plugins/examples/video_room.rs
> +        .room;
```suggestion
    let room_id = handle
        .create_room_with_config(
            VideoRoomCreateOptions {
                audiocodec: Some("opus".to_string()),
                videocodec: Some("h264".to_string()),
                notify_joining: Some(true),
                ..Default::default()
            },
            timeout,
        )
        .await?
        .room;
```

Not an important one, but we can provide the parameters we want and then use the default on other paramter if the struct implements `Default`

2024-08-30 09:19 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/events.rs
> +mod tests {
⭐ Thanks for the tests! It helped a lot with the review

2024-08-30 09:19 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/events.rs
> +                };
We can create an `Event` variant that holds another enum for the events so we can rely to do the pattern matching when parsing, instead of having ifs and elses

2024-08-30 09:19 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/events.rs
> +                };
The new variant can have the tag `event` and the enum it holds can be `untagged`, and in the `try_from` we bundle them up in a single enum

2024-08-30 09:19 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/events.rs
> +                };
Something similar to this
```rust
    #[serde(untagged)]
    VREvent(VrEvent),
}

#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Deserialize)]
#[serde(tag = "event")]
enum VrEvent {
    Error {
        error_code: u16,
        error: String,
    },
    Configured {
        room: Identifier,
        audio_codec: Option<String>,
        video_codec: Option<String>,
    },
    ConfiguredWithEstablishment {
        room: Identifier,
        audio_codec: Option<String>,
        video_codec: Option<String>,
        establishment_protocol: EstablishmentProtocol,
    },
    LeftRoom {
        room: Identifier,
        leaving: Identifier,
    },
}
```

2024-08-30 09:19 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/events.rs
> +                                  ),
```suggestion
                    data: json!({
                       "videoroom": "event",
                       "room": 8146468481724441u64,
                       "leaving": "ok"
                    }),
```

2024-09-08 20:56 UTC, koefmatt commented on jarust_plugins/src/video_room/events.rs
> +                };
Thanks for the advice! Based on that, I think I came up with a pretty clean solution. It's fairly robust so far, too. Many of the events aren't covered by tests since I'd like to get actual event data from Janus to test against. I'm not super confident in their documentation. I've resorted to reading the plugin's source code to get some of the missing details here. There are amazing things like "false" values never getting serialized: https://github.com/meetecho/janus-gateway/blob/master/src/plugins/janus_videoroom.c#L4279

2024-09-10 05:25 UTC, Ghamza-Jd commented on jarust_plugins/src/video_room/events.rs
> +                };
No worries, I can feel... when going for `1.0` we can hide untested (unit and manually) apis behind `unstable` feature until we verify its stable, and users could enable this flag explicitly.
Thanks!

2024-09-10 05:29 UTC, Ghamza-Jd approved these changes
⭐️

2024-09-10 05:30 UTC, merged